-- Create a custom type for the sender
create type public.sender as enum ('Noah', 'Jelili');

-- Create the messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  text text not null,
  sender public.sender not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

comment on table public.messages is 'Love journal messages between Noah and Jelili.';

-- Add row-level security
alter table public.messages enable row level security;

-- Since auth is handled on the frontend, we can create simple policies
-- that allow public access for now.
-- WARNING: This is permissive. You should tighten these rules
-- once you have an authentication strategy.

create policy "Public can read all messages"
  on public.messages for select
  using ( true );

create policy "Public can insert messages"
  on public.messages for insert
  with check ( true );
